// <auto-generated />
using Churn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Churn.Migrations
{
    [DbContext(typeof(ChurnCrmDbContext))]
    partial class ChurnCrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Churn.Models.Musteriler", b =>
                {
                    b.Property<int>("MusteriId")
                        .HasColumnType("int")
                        .HasColumnName("Musteri_ID");

                    b.Property<decimal>("AylikHarcamaTl")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Aylik_Harcama_TL");

                    b.Property<bool?>("ChurnDurumu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Churn_Durumu");

                    b.Property<int?>("DestekTalebiSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Destek_Talebi_Sayisi");

                    b.Property<int>("KullanimSuresiAy")
                        .HasColumnType("int")
                        .HasColumnName("Kullanim_Suresi_Ay");

                    b.Property<int>("SonGirisGunu")
                        .HasColumnType("int")
                        .HasColumnName("Son_Giris_Gunu");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("MusteriId")
                        .HasName("PK__Musteril__1E6CEE0AE1097A5D");

                    b.ToTable("Musteriler", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
